name: test-workflow
runs-on: ubuntu-latest
on:
 [push]
jobs:
 job1:
   uses: actions/checkout@v6.0.2
  with:
    # Repository name with owner. For example, actions/checkout
    repository: # optional, default is ${{ github.repository }}
    # The branch, tag or SHA to checkout. When checking out the repository that triggered a workflow, this defaults to the reference or SHA for that event.  Otherwise, uses the default branch.

 
