name: test-workflow
runs-on: ubuntu-latest
on:
 [push]
jobs:
 job1:
   name: "build"
   steps:
     - run:  echo "hi first job"
 job2:
  
  name: "test"
   steps:
      - needs: [job1]
      - run:  echo "hi second job"
